name: Ruby CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    name: Elixir CI
    runs-on: ${{ matrix.os }}
    env:
      MIX_ENV: test
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        rust:
          - stable

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Setup Rust 
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Setup Elixir Host SDK
        uses: erlef/setup-beam@v1
        with:
          experimental-otp: true
          otp-version: '25.0.4'
          elixir-version: '1.14.0'
      - name: Test Elixir Host SDK
        run: |
         LD_LIBRARY_PATH=/usr/local/lib make test

